
services:
  mariadb:
    container_name: mariadb
    image: mariadb:jonhan
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    privileged: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h mariadb -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'",
        ]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    env_file:
      - .env
    networks:
      - jonhan-network
    volumes:
      - mariaDB:/var/lib/mysql
    restart: always
    init: true
  nginx:
    restart: always
    depends_on:
      - wordpress
    image: nginx:jonhan
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    env_file:
      - .env
    ports:
      - '443:443'
    networks:
      - jonhan-network
    volumes:
      - wordpressDB:/var/www/html
  wordpress:
    container_name: wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    image: wordpress:jonhan
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - jonhan-network
    volumes:
      - wordpressDB:/var/www/html


volumes:
  wordpressDB:
    driver_opts:
      type: none
      device: /home/jonhan/data/wordpressDB
      o: bind
  mariaDB:
    driver_opts:
      type: none
      device: /home/jonhan/data/mariadb
      o: bind

networks:
  jonhan-network:
    driver: bridge